//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekzamen.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public System.DateTime datecreation { get; set; }
        public string orderstatus { get; set; }
        public string paymentstatus { get; set; }
        public string carelement { get; set; }
        public string details { get; set; }
        public int amountdamage { get; set; }
        public string liquids { get; set; }
        public int orderid { get; set; }
    }
}
